test: add the test scripts for testing on ESP32
** However, the two problems still exist.

1) The first one is that a thread cannot be created due to the memory problem --

./test_host_esp32.sh /dev/ttyUSB1
[Host] argv: ['', '/dev/ttyUSB1']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "serial_host.py", line 175, in run_tests
  File "secs.py", line 3344, in __init__
  File "secs.py", line 2428, in __init__
  File "secs.py", line 1330, in __init__
  File "threading.py", line 363, in start
OSError: can't create thread

So, I used the PSRAM version of ESP32, then I got the second problem:

2) Never ending recursion ?! --

./test_equipment_esp32.sh /dev/ttyUSB1
[Equipment] argv: ['', '/dev/ttyUSB1']
currentThread(): no current thread for 1073466596
[Equipment] wait for primary message...
maximum recursion depth exceeded
'NoneType' object has no attribute '__exit__'
'NoneType' object has no attribute '__exit__'
'NoneType' object has no attribute '__exit__'
...